version: "3.9"
services:
  vscode:
    build: .
    container_name: leptos-cf
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker-host.sock
      - type: bind
        source: ../
        target: /workspaces/leptos-cf
    init: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - devenv
networks:
  devenv:
